#!/bin/sh
#
# chkconfig: 2345 91 9
# description: Starts and stops the gbd_fit test daemon

LOCKFILE_PATH=/tmp/gbd_fit_test.lock

ulimit -c 10000000  # this enables a core dump if the program crashes

start() {
    python gbd_fit.py -d
    echo "started"
}
stop() {
    if [ -f $LOCKFILE_PATH ]; then
        PID=`cat $LOCKFILE_PATH`
        kill $PID
        echo "waiting for process to stop"
        sleep 10
        rm -f $LOCKFILE_PATH
        echo "stopped"
    else
	echo "gbd_fit test daemon is not running"
    fi
}

case $1 in
    restart)
	stop
	start
	;;
    start)
	start
	;;
    stop)
	stop
	;;
esac

