#!/bin/sh
#
# chkconfig: 2345 91 9
# description: Starts and stops the gbd_fit daemon

LOCKFILE_PATH=/tmp/gbd_fit.lock

ulimit -c 10000000  # this enables a core dump if the program crashes

start() {
    ./gbd_fit.sh -d
    echo "started"
}
stop() {
    if [ -f $LOCKFILE_PATH ]; then
        PID=`cat $LOCKFILE_PATH`
        kill $PID
        rm -f $LOCKFILE_PATH
        echo "stopped"
    else
	echo "gbd_fit daemon is not running"
    fi
}

case $1 in
    restart)
	stop
	start
	;;
    start)
	start
	;;
    stop)
	stop
	;;
esac

