#!/bin/bash

# start a bunch of non-automatic tests in the background

# fit rate functions
python2.5 manage.py run_tests rf increasing &
python2.5 manage.py run_tests rf unimodal &

# fit disease model
python2.5 manage.py run_tests dm &


# run automatic tests
python2.5 manage.py test