#!/bin/sh
#
# chkconfig: 2345 91 9
# description: Starts and stops the server_load daemon

LOCKFILE_PATH=/var/tmp/server_load.lock

ulimit -c 10000000  # this enables a core dump if the program crashes

start() {
    if [ -f $LOCKFILE_PATH ]; then
        echo "lock file exists"
    else
        python server_load.py
        echo "started"
    fi
}
stop() {
    if [ -f $LOCKFILE_PATH ]; then
        PID=`cat $LOCKFILE_PATH`
        kill $PID
        echo "waiting for process to stop"
        sleep 10
        rm -f $LOCKFILE_PATH
        echo "stopped"
    else
	echo "server_load daemon is not running"
    fi
}

case $1 in
    restart)
	stop
	start
	;;
    start)
	start
	;;
    stop)
	stop
	;;
esac

