#!/bin/bash

# start a bunch of non-automatic tests in the background

# fit rate functions
time python2.5 manage.py run_tests rf increasing &
time python2.5 manage.py run_tests rf unimodal &

# fit disease model
time python2.5 manage.py run_tests dm &


# run automatic tests
time python2.5 manage.py test